name: do_good_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  foldable_sidebar: ^1.0.0
  url_launcher: ^6.0.3
  font_awesome_flutter: ^9.0.0
  razorpay_flutter: ^1.2.1
  toast: ^0.1.5


  cupertino_icons: ^1.0.2
  animated_text_kit: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Kaushan
      fonts:
        - asset: fonts/Kaushan-Regular.ttf


